//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitecoreInstaller.Tests.Domain.Website {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebsiteTestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebsiteTestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SitecoreInstaller.Tests.Domain.Website.WebsiteTestResource", typeof(WebsiteTestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot; xmlns:x=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///&lt;sitecore&gt;
        ///&lt;events timingLevel=&quot;custom&quot;&gt;
        ///&lt;event name=&quot;forms:save&quot;&gt;
        ///
        ///      &lt;/event&gt;
        ///&lt;/events&gt;
        ///&lt;fieldTypes&gt;
        ///&lt;fieldType name=&quot;GroupList&quot; type=&quot;Sitecore.Form.Core.Fields.GroupListField,Sitecore.Forms.Core&quot;/&gt;
        ///&lt;/fieldTypes&gt;
        ///&lt;pipelines&gt;
        ///&lt;sessionEnd&gt;
        ///&lt;processor type=&quot;Sitecore.Form.Core.Pipeline.SessionEnd.RegisterFormDropouts, Sitecore.Forms.Core&quot; patch:before=&quot;processor[@type=&apos;Sitecore.Analytic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string formsOracle {
            get {
                return ResourceManager.GetString("formsOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot; xmlns:x=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///  &lt;sitecore&gt;
        ///
        ///    &lt;events timingLevel=&quot;custom&quot;&gt;
        ///      &lt;event name=&quot;forms:save&quot;&gt;
        ///
        ///      &lt;/event&gt;
        ///    &lt;/events&gt;
        ///
        ///    &lt;fieldTypes&gt;
        ///      &lt;fieldType name=&quot;GroupList&quot; type=&quot;Sitecore.Form.Core.Fields.GroupListField,Sitecore.Forms.Core&quot; /&gt;
        ///    &lt;/fieldTypes&gt;
        ///
        ///    &lt;pipelines&gt;
        ///
        ///      &lt;sessionEnd&gt;
        ///        &lt;processor type=&quot;Sitecore.Form.Core.Pipeline.SessionEnd.RegisterFormDropouts, Sitecore.For [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string formsSQL {
            get {
                return ResourceManager.GetString("formsSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot; xmlns:x=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///  &lt;sitecore&gt;
        ///
        ///    &lt;events timingLevel=&quot;custom&quot;&gt;
        ///      &lt;event name=&quot;forms:save&quot;&gt;
        ///
        ///      &lt;/event&gt;
        ///    &lt;/events&gt;
        ///
        ///    &lt;fieldTypes&gt;
        ///      &lt;fieldType name=&quot;GroupList&quot; type=&quot;Sitecore.Form.Core.Fields.GroupListField,Sitecore.Forms.Core&quot; /&gt;
        ///    &lt;/fieldTypes&gt;
        ///
        ///    &lt;pipelines&gt;
        ///
        ///      &lt;sessionEnd&gt;
        ///        &lt;processor type=&quot;Sitecore.Form.Core.Pipeline.SessionEnd.RegisterFormDropouts, Sitecore.For [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string formsSQLite {
            get {
                return ResourceManager.GetString("formsSQLite", resourceCulture);
            }
        }
    }
}
