#https://www.appveyor.com/docs/appveyor-yml
environment:
  VERSION_ASSEMBLY: 1.0.0
  VERSION_METADATA: -alpha1

version: "$(VERSION_ASSEMBLY)$(VERSION_METADATA)+{build}"

branches:
  only:
    - master

os: Visual Studio 2015

cache:
  - sitecoreinstaller\packages -> **\packages.config  # preserve "packages" directory but will reset it if packages.config is modified

init:
- ps: |
    #semver 1.0
    if($($env:VERSION_METADATA).length -gt 0) {
        #metadata has content which means we don't have a release
        $env:VERSION_SEM10 = "$($env:VERSION_ASSEMBLY)$($env:VERSION_METADATA)"
    }
    else {
        #release version
        $env:VERSION_SEM10 = "$($env:VERSION_ASSEMBLY)"
    }
    Write-Host "SemVer10: $($env:VERSION_SEM10)" 
    
install:
- ps: |
    $env:BUILD_COMMIT_SHORTHASH = "$env:APPVEYOR_REPO_COMMIT".substring(0,8);
    $env:VERSION_SEM20 = "$($env:VERSION_SEM10)+$($env:APPVEYOR_BUILD_NUMBER).$($env:BUILD_COMMIT_SHORTHASH)"

    Write-Host "SemVer20: $($env:VERSION_SEM20)"

- ps: |
    $assemblyInformationalVersionPresenceInAllFiles = $true
- ps: >-    
    Get-ChildItem $path -Filter "AssemblyInfo.cs" -recurse | Where-Object { $_.Attributes -ne "Directory"} |
        ForEach-Object { 
            Write-Host "Asserting $($_.FullName)"
            if (Get-Content $_.FullName | Select-String -Pattern "AssemblyInformationalVersion") {
                Write-Host "All good"
            }
            else {
                $assemblyInformationalVersionPresenceInAllFiles = $false
                Write-Warning "AssemblyInformationalVersion not found in  $($_.FullName)"
            }
        }
- ps: >-        
    if($assemblyInformationalVersionPresenceInAllFiles -eq $false) {
        throw "AssemblyInformationalVersion not found in all AssemblyInfo files"
    }  
    
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '$(VERSION_ASSEMBLY)'
  assembly_file_version: '$(VERSION_ASSEMBLY)'
  assembly_informational_version: '$(VERSION_SEM20)'

platform: Any CPU

configuration: release

build:
  parallel: true
  project: sitecoreinstaller.sln
  verbosity: normal

before_build:
- cmd: nuget restore sitecoreinstaller.sln

before_package:

after_build:
- cmd: nuget pack "SitecoreInstaller.Cmdlets\SitecoreInstaller.Cmdlets.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -version "%VERSION_SEM10%"

build_script:

test:
  assemblies:
    - '**\*.Tests.dll'

artifacts:
  - path: '*.nupkg'
    name: nugets