//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitecoreInstaller.Azure.Packaging.Databases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabasesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabasesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SitecoreInstaller.Azure.Packaging.Databases.DatabasesResources", typeof(DatabasesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --All dbs
        ///CREATE CLUSTERED INDEX ClusteredIndexForAzure ON ArchivedFields(RowId)
        ///CREATE CLUSTERED INDEX ClusteredIndexForAzure ON ArchivedItems(RowId)
        ///CREATE CLUSTERED INDEX ClusteredIndexForAzure ON Blobs(Id)
        ///CREATE CLUSTERED INDEX ClusteredIndexForAzure ON ClientData(Id)
        ///CREATE CLUSTERED INDEX ClusteredIndexForAzure ON History(Id)
        ///CREATE CLUSTERED INDEX ClusteredIndexForAzure ON IDTable(Id)
        ///CREATE CLUSTERED INDEX ClusteredIndexForAzure ON Items(Id)
        ///CREATE CLUSTERED INDEX ClusteredIndexForAzure ON  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddClusteredIndexesSql {
            get {
                return ResourceManager.GetString("AddClusteredIndexesSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Core Only
        ///CREATE CLUSTERED INDEX ClusteredIndexForAzure ON RolesInRoles(Id).
        /// </summary>
        internal static string AddClusteredIndexesSqlCoreOnly {
            get {
                return ResourceManager.GetString("AddClusteredIndexesSqlCoreOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER PROCEDURE [dbo].[aspnet_Membership_GetNumberOfUsersOnline]
        ///    @ApplicationName            nvarchar(256),
        ///    @MinutesSinceLastInActive   int,
        ///    @CurrentTimeUtc             datetime
        ///AS
        ///BEGIN
        ///    DECLARE @DateActive datetime
        ///    SELECT  @DateActive = DATEADD(minute,  -(@MinutesSinceLastInActive), @CurrentTimeUtc)
        ///
        ///    DECLARE @NumOnline int
        ///    SELECT  @NumOnline = COUNT(*)
        ///    FROM    dbo.aspnet_Users u WITH(NOLOCK),
        ///            dbo.aspnet_Applications a WITH(NOLOCK),
        ///            dbo.as [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddTableHintOnLocksSql {
            get {
                return ResourceManager.GetString("AddTableHintOnLocksSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC sp_dropextendedproperty 
        ///@name = N&apos;MS_DiagramPaneCount&apos;
        ///,@level0type = &apos;schema&apos; 
        ///,@level0name = dbo
        ///,@level1type = &apos;view&apos;
        ///,@level1name = &apos;Fields&apos;;
        ///
        ///EXEC sp_dropextendedproperty 
        ///@name = N&apos;MS_DiagramPane1&apos;
        ///,@level0type = &apos;schema&apos; 
        ///,@level0name = dbo
        ///,@level1type = &apos;view&apos;
        ///,@level1name = &apos;Fields&apos;;.
        /// </summary>
        internal static string DropExtendedPropertiesSql {
            get {
                return ResourceManager.GetString("DropExtendedPropertiesSql", resourceCulture);
            }
        }
    }
}
