//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitecoreInstaller.Domain.RuntimeServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuntimeServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuntimeServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SitecoreInstaller.Domain.RuntimeServices.RuntimeServiceResources", typeof(RuntimeServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; %&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;script runat=&quot;server&quot;&gt;
        ///
        ///    void Page_Load(object sender, System.EventArgs e)
        ///    {
        ///        Sitecore.Security.Authentication.AuthenticationManager.Login(@&quot;sitecore\admin&quot;, &quot;b&quot;);
        ///        HttpContext.Current.Response.Redirect(&quot;/sitecore&quot;);
        ///    }
        ///
        ///&lt;/script&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head runat=&quot;server&quot;&gt;
        ///    &lt;title&gt;Admin Login&lt;/title [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdminLogin {
            get {
                return ResourceManager.GetString("AdminLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; %&gt;
        ///
        ///&lt;%@ Import Namespace=&quot;Sitecore.Data.Serialization&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;System.IO&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Diagnostics&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.SecurityModel&quot; %&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;script runat=&quot;server&quot;&gt;
        ///  
        ///  protected void Page_Load(object sender, EventArgs e)
        ///  {
        ///    var serializationFolder = new DirectoryInfo(Sitecore.Data.Serialization.Pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeserializeItems {
            get {
                return ResourceManager.GetString("DeserializeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;System.IO&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Data.Engines&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Data.Proxies&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Diagnostics&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Install&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.SecurityModel&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Install.Metadata&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Install.Zip&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Update&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Update.Installer.Exceptions&quot; %&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstallPackageService {
            get {
                return ResourceManager.GetString("InstallPackageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; %&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;script runat=&quot;server&quot;&gt;
        ///  
        ///  private const string _packageStatusPath = &quot;/temp/SitecoreInstaller/PackageInstallStatus.txt&quot;;
        ///
        ///  protected void Page_Load(object sender, System.EventArgs e)
        ///  {
        ///    var packageName = System.Web.HttpContext.Current.Request.QueryString[&quot;Status&quot;];
        ///
        ///    if (packageName == null)
        ///    {
        ///      HttpContext.Current.Response.Statu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstallPackageStatusService {
            get {
                return ResourceManager.GetString("InstallPackageStatusService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; %&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;script runat=&quot;server&quot;&gt;
        ///
        ///    void Page_Load(object sender, System.EventArgs e)
        ///    {
        ///        var admin = Sitecore.Security.Accounts.User.FromName(@&quot;sitecore\admin&quot;, true);
        ///        var profile = admin.Profile;
        ///        profile[&quot;WallPaper&quot;] = string.Empty;
        ///        profile[&quot;Wallpaper&quot;] = string.Empty;
        ///        profile.Save();
        ///    }
        ///
        ///&lt;/script&gt;
        ///&lt;html xmln [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostInstallService {
            get {
                return ResourceManager.GetString("PostInstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Data&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Diagnostics&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.localhost&quot; %&gt;
        ///&lt;%@ Import Namespace=&quot;Sitecore.Tasks&quot; %&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;script runat=&quot;server&quot;&gt;
        ///
        ///  void Page_Load(object sender, System.EventArgs e)
        ///  {
        ///    //set context
        ///    Sitecore.Context.SetActiveSite(&quot;shell&quot;);
        ///    
        ///    Log.Info(&quot;&lt;SitecoreInstal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublishSiteService {
            get {
                return ResourceManager.GetString("PublishSiteService", resourceCulture);
            }
        }
    }
}
