//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitecoreInstaller.Domain.Website {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebsiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebsiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SitecoreInstaller.Domain.Website.WebsiteResource", typeof(WebsiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; %&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;script language=&quot;CS&quot; runat=&quot;server&quot;&gt;
        ///
        ///    void Page_Load(object sender, System.EventArgs e)
        ///    {
        ///        Sitecore.Security.Authentication.AuthenticationManager.Login(@&quot;sitecore\admin&quot;, &quot;b&quot;);
        ///        HttpContext.Current.Response.Redirect(&quot;/sitecore&quot;);
        ///    }
        ///
        ///&lt;/script&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head runat=&quot;server&quot;&gt;
        ///    &lt;title&gt;Ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdminLogin {
            get {
                return ResourceManager.GetString("AdminLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///    &lt;sitecore&gt;
        ///        &lt;sc.variable name=&quot;dataFolder&quot;&gt;
        ///            &lt;patch:attribute name=&quot;value&quot;&gt;{0}&lt;/patch:attribute&gt;
        ///        &lt;/sc.variable&gt;
        ///    &lt;/sitecore&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string DataFolderFormat {
            get {
                return ResourceManager.GetString("DataFolderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; %&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;script language=&quot;CS&quot; runat=&quot;server&quot;&gt;
        ///
        ///    protected void Page_Load(object sender, System.EventArgs e)
        ///    {
        ///        var packageName = System.Web.HttpContext.Current.Request.QueryString[&quot;Install&quot;];
        ///
        ///        if (packageName == null)
        ///            return;
        ///
        ///        packageName = System.Web.HttpUtility.UrlDecode(packageName);
        ///
        ///        var filename = Syste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstallPackageService {
            get {
                return ResourceManager.GetString("InstallPackageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///    &lt;sitecore&gt;
        ///        &lt;settings&gt;
        ///            &lt;setting  name=&quot;LicenseFile&quot;&gt;
        ///                &lt;patch:attribute name=&quot;value&quot;&gt;$(dataFolder)/{0}&lt;/patch:attribute&gt;
        ///            &lt;/setting &gt;
        ///        &lt;/settings&gt;
        ///    &lt;/sitecore&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string LicenseFileFormat {
            get {
                return ResourceManager.GetString("LicenseFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Language=&quot;C#&quot; %&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;script language=&quot;CS&quot; runat=&quot;server&quot;&gt;
        ///
        ///    void Page_Load(object sender, System.EventArgs e)
        ///    {
        ///        var admin = Sitecore.Security.Accounts.User.FromName(@&quot;sitecore\admin&quot;, true);
        ///        var profile = admin.Profile;
        ///        profile[&quot;WallPaper&quot;] = string.Empty;
        ///        profile.Save();
        ///    }
        ///
        ///&lt;/script&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostInstallService {
            get {
                return ResourceManager.GetString("PostInstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configuration xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot;&gt;
        ///    &lt;sitecore&gt;
        ///        &lt;formsDataProvider type=&quot;Sitecore.Forms.Data.DataProviders.WFMDataProvider,Sitecore.Forms.Core&quot;&gt;
        ///            &lt;param desc=&quot;connection string&quot;&gt;{0}&lt;/param&gt;
        ///        &lt;/formsDataProvider&gt;
        ///    &lt;/sitecore&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string WffmDataProviderFormat {
            get {
                return ResourceManager.GetString("WffmDataProviderFormat", resourceCulture);
            }
        }
    }
}
